### ISSUE TITLE
Aggiustare main

### ISSUE THREAD

**Issue by FabioZTessitore** [daniele998/helloworld#1]
l'istruzione return deve stare **dentro** alla funzione main

inoltre non serve il punto e virgola dopo la parentesi graffa

rifai tutti i passaggi come ti ho spiegato a partire dal pull

**Comment by daniele998** [comment]
fatto

**Comment by daniele998** [comment]
ho apportato le modifiche

2015-12-16 16:01 GMT+01:00 Fabio Z Tessitore notifications@github.com:
